export const ADD_CALENDAR_EVENT = 'ADD_CALENDAR_EVENT';
export const UPDATE_CALENDAR_EVENT = 'UPDATE_CALENDAR_EVENT';
export const REMOVE_CALENDAR_EVENT = 'REMOVE_CALENDAR_EVENT';
export const REMOVE_ALL_CALENDAR_EVENT = 'REMOVE_ALL_CALENDAR_EVENT';
export const EDIT_CALENDAR_EVENT = 'EDIT_CALENDAR_EVENT';
export const OPEN_DAY_EVENTS = 'OPEN_DAY_EVENTS';
export const CHANGE_MONTH = 'CHANGE_MONTH';


export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'
export const ASYNC_CALL_START = 'ASYNC_CALL_START'
export const ASYNC_CALL_END = 'ASYNC_CALL_END';